FONT_SIZES = {
    "x-small": 0.7,
    "smaller": 0.8,
    "small": 0.9,
    "normal": 1,
    "large": 1.1,
    "larger": 1.2,
    "x-large": 1.3
}

LOCALE_MAP = {
    "af": "Afrykanerski",
    "ar-dz": "Arabski (Algieria)",
    "ar-kw": "Arabski (Kuwejt)",
    "ar-ly": "Arabski (Libia)",
    "ar-ma": "Arabski (Maroko)",
    "ar-sa": "Arabski (Arabia Saudyjska)",
    "ar-tn": "Arabski (Tunezja)",
    "ar": "Arabski",
    "az": "Azerski",
    "bg": "Bułgarski",
    "bn": "Bengalski",
    "bs": "Bośniacki",
    "ca": "Kataloński",
    "cs": "Czeski",
    "cy": "Walijski",
    "da": "Duński",
    "de-at": "Niemiecki (Austria)",
    "de": "Niemiecki",
    "el": "Grecki",
    "en": "Angielski",
    "en-au": "Angielski (Australia)",
    "en-gb": "Angielski (Wielka Brytania)",
    "en-nz": "Angielski (Nowa Zelandia)",
    "eo": "Esperanto",
    "es-us": "Hiszpański (USA)",
    "es": "Hiszpański",
    "et": "Estoński",
    "eu": "Baskijski",
    "fa": "Perski",
    "fi": "Fiński",
    "fr-ca": "Francuski (Kanada)",
    "fr-ch": "Francuski (Szwajcaria)",
    "fr": "Francuski",
    "gl": "Galicyjski",
    "he": "Hebrajski",
    "hi": "Hindi",
    "hr": "Chorwacki",
    "hu": "Węgierski",
    "hy-am": "Ormiański",
    "id": "Indonezyjski",
    "is": "Islandzki",
    "it": "Włoski",
    "ja": "Japoński",
    "ka": "Gruziński",
    "kk": "Kazachski",
    "km": "Khmerski",
    "ko": "Koreański",
    "ku": "Kurdyjski",
    "lb": "Luksemburski",
    "lt": "Litewski",
    "lv": "Łotewski",
    "mk": "Macedoński",
    "ms": "Malajski",
    "nb": "Norweski Bokmål",
    "ne": "Nepalski",
    "nl": "Niderlandzki",
    "nn": "Norweski Nynorsk",
    "pl": "Polski",
    "pt-br": "Portugalski (Brazylia)",
    "pt": "Portugalski",
    "ro": "Rumuński",
    "ru": "Rosyjski",
    "si-lk": "Syngaleski (Sri Lanka)",
    "sk": "Słowacki",
    "sl": "Słoweński",
    "sm": "Samoański",
    "sq": "Albański",
    "sr-cyrl": "Serbski (cyrylica)",
    "sr": "Serbski (łacinka)",
    "sv": "Szwedzki",
    "ta-in": "Tamilski (Indie)",
    "th": "Tajski",
    "tr": "Turecki",
    "ug": "Ujgurski",
    "uk": "Ukraiński",
    "uz-cy": "Uzbecki (cyrylica)",
    "uz": "Uzbecki (łacinka)",
    "vi": "Wietnamski",
    "zh-cn": "Chiński (uproszczony)",
    "zh-tw": "Chiński (tradycyjny)"
}
